Ports Persistent Photoalbums from TG
ARF-SS13/coyote-bayou pull request #1788
Opened 2023-03-27 21:49 UTC by HanSolo1519

## About The Pull Request
like the title says
This is black magic to me, I just squinted at the code both here and on TG and it seemed similar.

May god spare my soul

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Added new things
/:cl:

2023-03-31 22:30 UTC, GremlingSS requested changes
ae

2023-03-31 22:30 UTC, GremlingSS commented on code/datums/traits/neutral.dm
> +	var/obj/item/storage/photo_album/personal/photo_album = new(get_turf(human_holder))
`var/obj/item/storage/photo_album/personal/photo_album`
to:
`var/obj/item/storage/photo_album/photo_album`

2023-03-31 22:30 UTC, GremlingSS commented on code/datums/traits/neutral.dm
> +	give_item_to_holder(photo_album, list(LOCATION_BACKPACK = ITEM_SLOT_BACKPACK, LOCATION_HANDS = ITEM_SLOT_HANDS))
```
give_item_to_holder(photo_album, list(LOCATION_BACKPACK = ITEM_SLOT_BACKPACK, LOCATION_HANDS = ITEM_SLOT_HANDS))
```
to:
```
if(!human_holder.equip_to_slot_if_possible(photo_album, SLOT_IN_BACKPACK, disable_warning = TRUE, bypass_equip_delay_self = TRUE)
    human_holder.put_in_hands(photo_album)
```

2023-03-31 22:30 UTC, GremlingSS commented on code/datums/traits/neutral.dm
> +	)
```
give_item_to_holder(
		/obj/item/camera,
		list(
			LOCATION_NECK = ITEM_SLOT_NECK,
			LOCATION_LPOCKET = ITEM_SLOT_LPOCKET,
			LOCATION_RPOCKET = ITEM_SLOT_RPOCKET,
			LOCATION_BACKPACK = ITEM_SLOT_BACKPACK,
			LOCATION_HANDS = ITEM_SLOT_HANDS
		)
	)
```
To:
```
var/obj/item/camera/cam = new(get_turf(human_holder))
if(!human_holder.equip_to_slot_if_possible(cam , SLOT_IN_BACKPACK, disable_warning = TRUE, bypass_equip_delay_self = TRUE)
    human_holder.put_in_hands(cam)
```

2023-04-07 21:57 UTC, Superlagg approved these changes

2023-04-07 21:58 UTC, GremlingSS approved these changes
okidoki

2023-04-07 21:58 UTC, merged