Shameless rider kit buff (and to some degree, beastmaster buff)
ARF-SS13/coyote-bayou pull request #3233
Opened 2023-10-01 06:58 UTC by RinPin

adds a capture device to the rider kit, so it's a lot easier to have your own pet chocobo / motorcycle without them constantly dying due to ghouls attacking them or getting stolen due to the lack of keys, buffs beastmaster by adding an additional capture egg to the kit, to hopefully encourage more diversity in battle pets, (i'll probably make an eggless version of the rider kit for cargo if people abuse this)

## About The Pull Request

## Pre-Merge Checklist
- [Y ] You tested this on a local server.
- [ Y] This code did not runtime during testing.
- [ Y] You documented all of your changes.

2023-10-01 17:32 UTC, RinPin commented
Oh god linter BS, I’ll solve this when I get home

2023-10-02 13:03 UTC, Tk420634 commented
Beat it with a rock, rin

2023-10-03 02:37 UTC, DameonOwen requested changes

2023-10-03 02:37 UTC, DameonOwen commented on code/game/objects/items/loadout_toolkits.dm
> +		/obj/item/capturedevice(src)
`new` in front if this

2023-10-03 02:37 UTC, DameonOwen commented on code/game/objects/items/loadout_toolkits.dm
> +		/obj/item/capturedevice(src)//hopefully this will make having a pet motorcycle a lot less annoying
`new` in front of this

2023-10-03 02:37 UTC, DameonOwen commented on code/game/objects/items/loadout_toolkits.dm
> +        /object
Remove this line

2023-10-03 02:50 UTC, DameonOwen approved these changes

2023-10-03 02:51 UTC, merged