Add minimum flavortext length, always let ghosts see flavortexts
ARF-SS13/coyote-bayou pull request #794
Opened 2022-09-17 19:16 UTC by out-of-phaze

## About The Pull Request
Rewrites #764 for better code quality and to fix the inverted checks.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Adds a minimum flavortext length
tweak: Allows ghosts to always see character flavortext, even when someone is wearing a mask.
/:cl:

2022-09-17 19:25 UTC, out-of-phaze commented on code/modules/mob/dead/new_player/new_player.dm
> +		if(SSticker.current_state >= GAME_STATE_PREGAME && tready == PLAYER_READY_TO_OBSERVE)
It's still weird logic, but yeah, I forgot to remove it.

2022-09-17 19:27 UTC, out-of-phaze commented on code/modules/mob/dead/new_player/new_player.dm
> +			to_chat(client.mob, span_danger("Your flavortext does not meet the minimum of [MIN_FLAVOR_LEN] characters."))
I wasn't trying to fix the code repetition? The main issue I'm fixing is that your checks were backwards.
It's inside `AttemptLateSpawn()` which is what `if(href_list["SelectedJob"])` calls. There's no way to get around that with an href exploit.

Moreover, AFAIK there's no reason to restrict ghost role spawning based on currently selected flavortext. It doesn't ever even load the prefs for that character even when spawning a humantype.

2022-09-17 20:58 UTC, out-of-phaze commented on code/datums/elements/flavor_text.dm
> +	if(!always_show && isliving(target) && !isobserver(user))
What the *fuck?* Why would anything do that???

2022-09-20 06:59 UTC, thingpony commented
Hey there! Just change the requirement from 130 down to 100 and this will be good to go.

2022-09-20 18:25 UTC, thingpony requested changes
Just change this :
#define MIN_FLAVOR_LEN 130
to 
#define MIN_FLAVOR_LEN 100

2022-09-21 00:37 UTC, Superlagg approved these changes

2022-09-21 05:56 UTC, thingpony approved these changes

2022-09-21 17:49 UTC, merged