Nerfs supermutant behemoth
ARF-SS13/coyote-bayou pull request #852
Opened 2022-09-27 17:48 UTC by Yawet330

Bearrr did not fix the issue with stomps being spammed.
Infact, past the 300 hp decrease they basically buffed it as they gave it the extra damage without debuffing its AP

Essentially fixes the fact Bearrr stealth-buffed its damage output without fixing the actual bug with the Behemoths 'admittedly' peabrained AI.

Come on, man.

AAAAAAAAAAAA
## Changelog
:cl:
fix: Stomps can no longer be spammed by the player, or by the mobs. Now on a 150 tick CD
tweak: You're not supposed to be 1 shot through heavy armor, even at range. Prevents the walk stomp from going through walls, massively increases player chance against it by removing the stomping in phase 1; reverts the stealth-buff done to its strength.
/:cl:

2022-09-27 19:12 UTC, Superlagg requested changes
Keep in mind, this is a huge melee focused monster, it's supposed to be next to impossible to take down in melee, even with minmaxed melee builds. Melee isnt the answer to everything, and the encounter is more than doable with a gun.

2022-09-27 19:12 UTC, Superlagg commented on code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
> +	var/stomp_cooldown = 150 // WOW WHO WOULD HAVE THOUGHT?
Please use a define for timing, SECONDS

2022-09-27 19:12 UTC, Superlagg commented on code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
> +	var/stomp_cooldown = 150 // WOW WHO WOULD HAVE THOUGHT?
Also for cooldowns, use a cooldown define, like COOLDOWN_DECLARE.

2022-09-27 19:12 UTC, Superlagg commented on code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
> +				if(world.time >= stomp_cooldown)
Please use a cooldown define, and an early return if possible,

2022-09-27 19:12 UTC, Superlagg commented on code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
> +			if(world.time >= stomp_cooldown)
Same with the cooldown define and early return.

2022-09-28 01:39 UTC, bearrrrrrrr commented
pretty hesitant for all of these changes. i can already solo the behemoth at ranged. these changes make it extremely easy to an even larger extent- in the case i got caught in a bad situation, i recieved actual implications. here? i don't think there's gonna be a lot.

this PR is a no from me chief, sorry.

2022-09-29 23:09 UTC, gozulio commented
I swear this PR is half code and half you talking to yourself in code comments.

2022-09-29 23:48 UTC, gozulio commented on code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
> +		stomp_range = 2 //Please do not make a 4x4 death zone that goes through walls whenever it walks... Which it does... Very quickly.
Why does this need to be commented? I think this var is relatively self evident.

2022-09-29 23:54 UTC, gozulio commented on code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
> +	maxHealth = 2300 //I actually see why this needs to be higher. I almost killed it with a Bozar in under 20 seconds via just holding LMB at PB range
Probably put these back to 3000. This a boss guarding power armor. So far as I can tell you're doing your testing Solo against this boss and no one should be Solo fighting this boss.

2022-09-29 23:57 UTC, gozulio commented
> > I swear this PR is half code and half you talking to yourself in code comments.
> 
> You have no idea the levels of insanity I have achieved.
> 
> Code comments also help to let future coders understand that this piece of code may have problematic issues if changed, as in //HOLY FUCK THIS WILL BREAK DO NOT TOUCH THIS.
> 
> In a way your git contribution standards file may not. (like how we use a different cooldown system than: everywhere)

I know what code comments do.
and despite mentioning the separate cooldown system (which to be fair, I just learned about tonight.) you don't actually comment on the use of the cooldown define.

2022-09-30 00:02 UTC, Tk420634 commented
25 comments, labeling this a salt pr now :3

2022-09-30 00:48 UTC, gozulio commented
You're also going to need to compile and actually test to make sure this doesn't crash on a local server. AFAICT your PR does not indicate whether or not you have compiled and tested how this code actually functions. Furthermore I've been told your changes are more based on your experiences with the boss in it's current, live server state then  how the modified version in your coding branch.

2022-09-30 00:51 UTC, closed without merging