Solves Merge Conflicts with #963
ARF-SS13/coyote-bayou pull request #968
Opened 2022-10-13 15:56 UTC by WrongEnd

## About The Pull Request
Solves merge conflicts with #963 as per request of @out-of-phaze 

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2022-10-13 20:51 UTC, Superlagg requested changes
I'm also going to wait for Phaze's approval, they know a lot more about this stuff than I do.

2022-10-13 20:51 UTC, Superlagg commented on _maps/map_files/Pahrump-Sunset/RockSprings.dmm
> +	doc_content_4 = "hi i gues, me n mi pals fund thiz old comouter   we thnk u smel lik shjt;"
might want to put the " before the ;

2022-10-14 13:36 UTC, out-of-phaze approved these changes
Well, it passes CI now, so it's an improvement no matter what. Ignore the mapdiffbot thing, that's because it's comparing it to the map prior to the fixes, which makes it die before it finishes. It's not actually still running, it's just a timestamp.

2022-10-14 22:31 UTC, Superlagg approved these changes

2022-10-14 22:31 UTC, merged